### PR TITLE
fix(tasks): Reference the correct secret

### LINKED ISSUE #144: Tasks are using the wrong secret
**Describe the bug**
When a tekton task is run, it is unable to start since it is trying to read the wrong secret. It is reading `peribolos-$(params.INSTALLATION-ID)` instead of `$(params.SECRET_NAME)`.

**To Reproduce**
1. Install the app on in a new organization
2. Check the logs of the `dump-config` TaskRun

**Expected behavior**
It should read the correct secret.

### PR DESCRIPTION
**Pull request by SamoKopecky**
Resolves #144

### CODE REVIEW

**Review by KPostOffice — COMMENTED** [review]
/lgtm

Looks like a straight forward fix

**Comment by tumido** [comment]
This is not right, merging changes to manifest base would update production manifests. This changeset was introduced via https://github.com/open-services-group/peribolos-as-a-service/pull/138 and is already applied to dev overlay, see: 

https://github.com/open-services-group/peribolos-as-a-service/blob/main/manifests/overlays/dev/kustomization.yaml

**Comment by tumido** [comment]
Superseded by #156 (cherry-picked into).

**Pull request closed without merging**
